# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dominio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=14)),
                ('telefono', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField()),
                ('fecha_fundacion', models.DateField()),
                ('presidente', models.CharField(max_length=50)),
                ('director_institucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('institucion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.PerfilInstitucion')),
            ],
        ),
    ]
